<?php

namespace Nachopitt\Migrations\Tests;

use Nachopitt\Migrations\Writers\MigrationDefinitionWriter;
use PhpMyAdmin\SqlParser\Parser;
use PhpMyAdmin\SqlParser\Statements\CreateStatement;
use PHPUnit\Framework\TestCase;

class GenerateMigrationTest extends TestCase
{
    private static string $generatedMigration;

    public static function setUpBeforeClass(): void
    {
        self::$generatedMigration = self::buildGeneratedMigration();
    }

    public function test_generates_migration_file_structure()
    {
        $this->assertStringContainsString("<?php\n\nuse Illuminate\\Database\\Migrations\\Migration;", self::$generatedMigration);
        $this->assertStringContainsString('return new class extends Migration', self::$generatedMigration);
        $this->assertStringContainsString('public function up()', self::$generatedMigration);
        $this->assertStringContainsString('public function down()', self::$generatedMigration);
    }

    public function test_wraps_up_and_down_in_without_foreign_key_constraints()
    {
        $this->assertSame(2, substr_count(self::$generatedMigration, 'Schema::withoutForeignKeyConstraints(function () {'));
    }

    public function test_generates_project_tag_table_definition()
    {
      $this->assertStringContainsString("Schema::create('project_tag', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('project_id', 'fk_project_tag_projects1')", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('tag_id', 'fk_project_tag_tags1')", self::$generatedMigration);
    }

    public function test_generates_project_updates_table_definition()
    {
      $this->assertStringContainsString("Schema::create('project_updates', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->fullText('description', 'project_updates_description_FULLTEXT');", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('updater_user_id', 'fk_project_updates_users1')", self::$generatedMigration);
    }

    public function test_generates_projects_table_definition()
    {
      $this->assertStringContainsString("Schema::create('projects', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->fullText('title', 'projects_title_FULLTEXT');", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('assigned_user_id', 'fk_projects_users2')", self::$generatedMigration);
    }

    public function test_generates_tags_table_definition()
    {
      $this->assertStringContainsString("Schema::create('tags', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->unique('name', 'name_UNIQUE');", self::$generatedMigration);
    }

    public function test_generates_user_profiles_table_definition()
    {
      $this->assertStringContainsString("Schema::create('user_profiles', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->unique('user_id', 'user_id_UNIQUE');", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('user_id', 'fk_user_profiles_users1')", self::$generatedMigration);
    }

    public function test_generates_user_roles_table_definition()
    {
      $this->assertStringContainsString("Schema::create('user_roles', function (Blueprint \$table) {", self::$generatedMigration);
      $this->assertStringContainsString("\$table->foreign('user_id', 'fk_user_roles_users1')", self::$generatedMigration);
    }

    public function test_generates_down_method_with_expected_drop_order()
    {
        $expectedDrops = [
            "Schema::dropIfExists('project_tag');",
            "Schema::dropIfExists('project_updates');",
            "Schema::dropIfExists('projects');",
            "Schema::dropIfExists('tags');",
            "Schema::dropIfExists('user_profiles');",
            "Schema::dropIfExists('user_roles');",
        ];

        $lastPosition = -1;

        foreach ($expectedDrops as $dropStatement) {
            $position = strpos(self::$generatedMigration, $dropStatement);
            $this->assertNotFalse($position, "Missing drop statement: {$dropStatement}");
            $this->assertGreaterThan($lastPosition, $position, "Drop statement out of order: {$dropStatement}");
            $lastPosition = $position;
        }
    }

    private static function buildGeneratedMigration(): string
    {
        $sql = <<<'SQL'
-- MySQL Script generated by MySQL Workbench
-- Fri Sep 19 08:46:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `project_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `tag_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_tag_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_project_tag_tags1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_tag_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_tag_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_updates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_updates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `progress_percentage` TINYINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `updater_user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_updates_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_project_updates_users1_idx` (`updater_user_id` ASC) VISIBLE,
  FULLTEXT INDEX `project_updates_description_FULLTEXT` (`description`) VISIBLE,
  CONSTRAINT `fk_project_updates_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_updates_users1`
    FOREIGN KEY (`updater_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `priority` VARCHAR(20) NOT NULL,
  `current_status` VARCHAR(20) NOT NULL,
  `current_progress_percentage` TINYINT UNSIGNED NOT NULL,
  `start_date` DATE NULL,
  `due_date` DATE NULL,
  `end_date` DATE NULL,
  `parent_id` BIGINT UNSIGNED NULL,
  `reporter_user_id` BIGINT UNSIGNED NOT NULL,
  `assigned_user_id` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_projects1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_projects_users1_idx` (`reporter_user_id` ASC) VISIBLE,
  INDEX `fk_projects_users2_idx` (`assigned_user_id` ASC) VISIBLE,
  FULLTEXT INDEX `projects_title_FULLTEXT` (`title`) VISIBLE,
  FULLTEXT INDEX `projects_description_FULLTEXT` (`description`) VISIBLE,
  CONSTRAINT `fk_projects_projects1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`reporter_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users2`
    FOREIGN KEY (`assigned_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_profiles_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profiles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_roles_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SQL;

        $parser = new Parser($sql);
        $migrationWriter = new MigrationDefinitionWriter();

        // mimic squash + withoutForeignKeyConstraints behavior
        $migrationWriter->reset();
        $migrationWriter->beginWithoutForeignKeyConstraints();

        foreach ($parser->statements as $statement) {
            if ($statement instanceof CreateStatement && in_array('TABLE', $statement->options->options)) {
                $migrationWriter->handleCreateTableStatement($statement);
            }
        }

        $migrationWriter->endWithoutForeignKeyConstraints();

        $up = $migrationWriter->getUpDefinition();
        $down = $migrationWriter->getDownDefinition();

        $stub = file_get_contents(__DIR__ . '/../src/stubs/migration.create.stub');

        $generated = str_replace(['DummyUpDefinition', '{{ upDefinition }}', '{{upDefinition}}'], $up, $stub);
        $generated = str_replace(['DummyDownDefinition', '{{ downDefinition }}', '{{downDefinition}}'], $down, $generated);

        return rtrim(str_replace(["\r\n", "\r"], "\n", $generated));
    }
}
