<?php

namespace Nachopitt\Migrations\Tests;

use Nachopitt\Migrations\Writers\MigrationDefinitionWriter;
use PhpMyAdmin\SqlParser\Parser;
use PhpMyAdmin\SqlParser\Statements\CreateStatement;
use PHPUnit\Framework\TestCase;

class GenerateMigrationTest extends TestCase
{
    public function test_generates_expected_migration_from_mysql_sql()
    {
        $sql = <<<'SQL'
-- MySQL Script generated by MySQL Workbench
-- Fri Sep 19 08:46:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `project_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `tag_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_tag_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_project_tag_tags1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_tag_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_tag_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_updates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_updates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `progress_percentage` TINYINT UNSIGNED NOT NULL,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `updater_user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_updates_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_project_updates_users1_idx` (`updater_user_id` ASC) VISIBLE,
  FULLTEXT INDEX `project_updates_description_FULLTEXT` (`description`) VISIBLE,
  CONSTRAINT `fk_project_updates_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_updates_users1`
    FOREIGN KEY (`updater_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `priority` VARCHAR(20) NOT NULL,
  `current_status` VARCHAR(20) NOT NULL,
  `current_progress_percentage` TINYINT UNSIGNED NOT NULL,
  `start_date` DATE NULL,
  `due_date` DATE NULL,
  `end_date` DATE NULL,
  `parent_id` BIGINT UNSIGNED NULL,
  `reporter_user_id` BIGINT UNSIGNED NOT NULL,
  `assigned_user_id` BIGINT UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_projects1_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_projects_users1_idx` (`reporter_user_id` ASC) VISIBLE,
  INDEX `fk_projects_users2_idx` (`assigned_user_id` ASC) VISIBLE,
  FULLTEXT INDEX `projects_title_FULLTEXT` (`title`) VISIBLE,
  FULLTEXT INDEX `projects_description_FULLTEXT` (`description`) VISIBLE,
  CONSTRAINT `fk_projects_projects1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`reporter_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_users2`
    FOREIGN KEY (`assigned_user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_profiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_profiles_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profiles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_roles_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SQL;

        $parser = new Parser($sql);
        $migrationWriter = new MigrationDefinitionWriter();

        // mimic squash + withoutForeignKeyConstraints behavior
        $migrationWriter->reset();
        $migrationWriter->beginWithoutForeignKeyConstraints();

        foreach ($parser->statements as $statement) {
            if ($statement instanceof CreateStatement && in_array('TABLE', $statement->options->options)) {
                $migrationWriter->handleCreateTableStatement($statement);
            }
        }

        $migrationWriter->endWithoutForeignKeyConstraints();

        $up = $migrationWriter->getUpDefinition();
        $down = $migrationWriter->getDownDefinition();

        $stub = file_get_contents(__DIR__ . '/../src/stubs/migration.create.stub');

        $generated = str_replace(['DummyUpDefinition', '{{ upDefinition }}', '{{upDefinition}}'], $up, $stub);
        $generated = str_replace(['DummyDownDefinition', '{{ downDefinition }}', '{{downDefinition}}'], $down, $generated);

        $expected = <<<'PHP'
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::withoutForeignKeyConstraints(function () {
            Schema::create('project_tag', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->bigInteger('project_id')
                    ->unsigned();
                $table->bigInteger('tag_id')
                    ->unsigned();
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->primary('id', null);
                $table->index('project_id', 'fk_project_tag_projects1_idx');
                $table->index('tag_id', 'fk_project_tag_tags1_idx');
                $table->foreign('project_id', 'fk_project_tag_projects1')
                    ->references('id')
                    ->on('projects')->onDelete('no action')->onUpdate('no action');
                $table->foreign('tag_id', 'fk_project_tag_tags1')
                    ->references('id')
                    ->on('tags')->onDelete('no action')->onUpdate('no action');
            });
            Schema::create('project_updates', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->text('description');
                $table->string('status', 20);
                $table->tinyInteger('progress_percentage')
                    ->unsigned();
                $table->bigInteger('project_id')
                    ->unsigned();
                $table->bigInteger('updater_user_id')
                    ->unsigned();
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->timestamp('deleted_at')
                    ->nullable();
                $table->primary('id', null);
                $table->index('project_id', 'fk_project_updates_projects1_idx');
                $table->index('updater_user_id', 'fk_project_updates_users1_idx');
                $table->fullText('description', 'project_updates_description_FULLTEXT');
                $table->foreign('project_id', 'fk_project_updates_projects1')
                    ->references('id')
                    ->on('projects')->onDelete('no action')->onUpdate('no action');
                $table->foreign('updater_user_id', 'fk_project_updates_users1')
                    ->references('id')
                    ->on('users')->onDelete('no action')->onUpdate('no action');
            });
            Schema::create('projects', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->string('title', 255);
                $table->text('description')
                    ->nullable();
                $table->string('priority', 20);
                $table->string('current_status', 20);
                $table->tinyInteger('current_progress_percentage')
                    ->unsigned();
                $table->date('start_date')
                    ->nullable();
                $table->date('due_date')
                    ->nullable();
                $table->date('end_date')
                    ->nullable();
                $table->bigInteger('parent_id')
                    ->unsigned()
                    ->nullable();
                $table->bigInteger('reporter_user_id')
                    ->unsigned();
                $table->bigInteger('assigned_user_id')
                    ->unsigned()
                    ->nullable();
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->timestamp('deleted_at')
                    ->nullable();
                $table->primary('id', null);
                $table->index('parent_id', 'fk_projects_projects1_idx');
                $table->index('reporter_user_id', 'fk_projects_users1_idx');
                $table->index('assigned_user_id', 'fk_projects_users2_idx');
                $table->fullText('title', 'projects_title_FULLTEXT');
                $table->fullText('description', 'projects_description_FULLTEXT');
                $table->foreign('parent_id', 'fk_projects_projects1')
                    ->references('id')
                    ->on('projects')->onDelete('no action')->onUpdate('no action');
                $table->foreign('reporter_user_id', 'fk_projects_users1')
                    ->references('id')
                    ->on('users')->onDelete('no action')->onUpdate('no action');
                $table->foreign('assigned_user_id', 'fk_projects_users2')
                    ->references('id')
                    ->on('users')->onDelete('no action')->onUpdate('no action');
            });
            Schema::create('tags', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->string('name', 255);
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->timestamp('deleted_at')
                    ->nullable();
                $table->primary('id', null);
                $table->unique('name', 'name_UNIQUE');
            });
            Schema::create('user_profiles', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->string('first_name', 255);
                $table->string('last_name', 255);
                $table->tinyInteger('active')
                    ->unsigned();
                $table->bigInteger('user_id')
                    ->unsigned();
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->primary('id', null);
                $table->index('user_id', 'fk_user_profiles_users1_idx');
                $table->unique('user_id', 'user_id_UNIQUE');
                $table->foreign('user_id', 'fk_user_profiles_users1')
                    ->references('id')
                    ->on('users')->onDelete('no action')->onUpdate('no action');
            });
            Schema::create('user_roles', function (Blueprint $table) {
                $table->bigInteger('id')
                    ->unsigned()
                    ->autoIncrement();
                $table->string('role', 20);
                $table->bigInteger('user_id')
                    ->unsigned();
                $table->timestamp('created_at')
                    ->nullable();
                $table->timestamp('updated_at')
                    ->nullable();
                $table->primary('id', null);
                $table->index('user_id', 'fk_user_roles_users1_idx');
                $table->foreign('user_id', 'fk_user_roles_users1')
                    ->references('id')
                    ->on('users')->onDelete('no action')->onUpdate('no action');
            });
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::withoutForeignKeyConstraints(function () {
            Schema::dropIfExists('project_tag');
            Schema::dropIfExists('project_updates');
            Schema::dropIfExists('projects');
            Schema::dropIfExists('tags');
            Schema::dropIfExists('user_profiles');
            Schema::dropIfExists('user_roles');
        });
    }
};
PHP;

        // Normalize line endings and trim trailing newlines to avoid platform differences
        $generatedNormalized = rtrim(str_replace(["\r\n", "\r"], "\n", $generated));
        $expectedNormalized = rtrim(str_replace(["\r\n", "\r"], "\n", $expected));

        $this->assertSame($expectedNormalized, $generatedNormalized);
    }
}
